### proper request
POST http://192.168.1.9/abf-browser/api/v3/abf-info/
content-type: application/json  HTTP/1.1

{
    "abf-path": "X:/Data/2P01/2016/non-publish/2016-07-11 PIR TR IHC/16711000.abf"
}

### missing abf-path
POST http://192.168.1.9/abf-browser/api/v3/abf-info/
Content-Type: application/json

{
    "abf-path": "X:/Data/missing.abf"
}

### missing abf-path
POST http://192.168.1.9/abf-browser/api/v3/abf-info/
Content-Type: application/json

{
    "test": "123"
}

### path with backslashes
POST http://192.168.1.9/abf-browser/api/v3/abf-info/
Content-Type: application/json

{
    "abf-path": "X:\\Data\\demo.abf"
}

### empty body
POST http://192.168.1.9/abf-browser/api/v3/abf-info/
Content-Type: application/json


### bad method type
GET http://192.168.1.9/abf-browser/api/v3/abf-info/
Content-Type: application/json

