### proper request
GET http://192.168.1.9/abf-browser/api/v3/abf-list/
content-type: application/json  HTTP/1.1

{
    "abf-path": "X:/Data/2P01/2016/non-publish/2016-07-11 PIR TR IHC"
}

### missing abf-path
POST http://192.168.1.9/abf-browser/api/v3/abf-list/
Content-Type: application/json

{
    "abf-path": "X:/Data/missing"
}

### missing abf-path
POST http://192.168.1.9/abf-browser/api/v3/abf-list/
Content-Type: application/json

{
    "test": "123"
}

### path with backslashes
POST http://192.168.1.9/abf-browser/api/v3/abf-list/
Content-Type: application/json

{
    "abf-path": "X:\\Data"
}

### empty body
POST http://192.168.1.9/abf-browser/api/v3/abf-list/
Content-Type: application/json


### bad method type
GET http://192.168.1.9/abf-browser/api/v3/abf-list/
Content-Type: application/json

